export interface Industry {
  slug: string;
  name: string;
  headline: string;
  description: string;
  challenges: string[];
  solutions: string[];
  compliance: string[];
}

export const industries: Industry[] = [
  { slug: "bfsi", name: "Banking & Financial Services", headline: "Enterprise AI Security for Banking, Financial Services & Insurance", description: "BFSI teams operate under the highest regulatory scrutiny and threat exposure of any sector. AEGIBIT VoiceCore is built to meet RBI cybersecurity framework requirements with voice biometric authentication, immutable audit trails, and RBAC aligned to your org's risk tolerance.", challenges: ["RBI cybersecurity framework compliance", "Insider threat risk on high-value transactions", "Multi-system approval workflows", "Real-time regulatory reporting"], solutions: ["Voice biometric authentication on every command", "Dual-approval (Sudo Mode) for high-value operations", "Immutable audit trail meets RBI evidence requirements", "Anomaly detection for insider threat detection"], compliance: ["RBI Cybersecurity Framework", "SEBI CSCRF", "DPDP Act 2023", "ISO 27001"] },
  { slug: "healthcare", name: "Healthcare & Life Sciences", headline: "HIPAA-Aligned AI Voice Infrastructure for Healthcare", description: "Healthcare teams need voice AI that moves at clinical speed without compromising patient data. VoiceCore provides HIPAA-aligned voice automation with India data residency, hands-free clinical commands, and a complete patient data audit trail.", challenges: ["HIPAA compliance for patient data", "Hands-free operation in clinical environments", "Identity verification for rotating staff", "Data sovereignty requirements"], solutions: ["Voice-authenticated EHR access without touching a screen", "Full HIPAA audit trail on every patient data access", "India data residency for complete data sovereignty", "RBAC maps directly to clinical role hierarchy"], compliance: ["HIPAA", "DPDP Act 2023", "NABH Guidelines", "ISO 27799"] },
  { slug: "government", name: "Government & Defense", headline: "Sovereign AI Infrastructure for Government Operations", description: "Government bodies require data sovereignty, full auditability, and operational reliability above all else. VoiceCore's on-premise deployment, India-only data residency, and air-gap capable architecture make it the only viable voice AI platform for government workloads.", challenges: ["Data sovereignty mandated by policy", "No third-party data sharing allowed", "High-security classification requirements", "Legacy system integration"], solutions: ["On-premise deployment with no external data egress", "India-only data residency by design", "Air-gap capable for classified environments", "Full audit trail with tamper-proof evidence chain"], compliance: ["MeitY Security Guidelines", "CERT-In Framework", "NIC Security Policy", "ISO 27001"] },
  { slug: "telecom", name: "Telecommunications", headline: "AI Voice Operations for Telecom Enterprise Teams", description: "Telecom operations teams manage massive, distributed infrastructure. VoiceCore gives NOC and security teams voice-authenticated control over their entire toolstack with real-time audit logging.", challenges: ["Distributed NOC team coordination", "High-volume incident management", "Network change audit requirements", "24/7 operational continuity"], solutions: ["Voice-command NOC workflows across distributed teams", "Biometric authentication for network change approvals", "Full audit trail for all infrastructure commands", "SIEM integration for voice-queried security events"], compliance: ["TRAI Guidelines", "DoT Security Framework", "ISO 27001", "DPDP Act 2023"] },
  { slug: "manufacturing", name: "Manufacturing & Industrial", headline: "Voice-Authenticated Operations for Manufacturing Teams", description: "Manufacturing floors demand hands-free operation and zero-error command execution. VoiceCore provides biometric-authenticated voice commands for OT/IT teams with complete operational audit trails.", challenges: ["Hands-free operation in production environments", "OT/IT security boundary management", "Shift handoff documentation", "Regulatory compliance for industrial operations"], solutions: ["Hands-free biometric authentication via voice", "OT system integration with RBAC isolation", "Auto-documented shift handoff with voice commands", "Full operational audit trail for regulatory compliance"], compliance: ["ISO 27001", "IEC 62443", "DPDP Act 2023", "BIS Industrial Standards"] },
  { slug: "education", name: "Higher Education & Research", headline: "Secure Voice AI for Universities and Research Institutions", description: "Higher education institutions manage sensitive research data, student records, and complex multi-stakeholder environments. VoiceCore provides role-aware voice automation with research data protection.", challenges: ["Student data privacy requirements", "Research IP protection", "Multi-role stakeholder access (faculty, admin, IT)", "Distributed campus operations"], solutions: ["FERPA-aligned student data access controls", "Research data isolation via RBAC", "Role-mapped voice commands for faculty vs admin vs IT", "Full data access audit trail for compliance"], compliance: ["FERPA", "DPDP Act 2023", "UGC Data Protection Guidelines", "ISO 27001"] },
];
