export interface Integration {
  slug: string;
  name: string;
  category: string;
  headline: string;
  description: string;
  commands: string[];
  setupSteps: string[];
}

export const integrations: Integration[] = [
  { slug: "google-calendar", name: "Google Calendar", category: "Productivity", headline: "Voice-Command Your Google Calendar", description: "Schedule meetings, block focus time, and check your agenda — all via authenticated voice commands that log every action.", commands: ["Schedule meeting with security team tomorrow at 10am", "Block my calendar Friday afternoon", "Show my agenda for today", "Cancel 3pm meeting and notify attendees"], setupSteps: ["Connect Google Workspace in VoiceCore settings", "Authorize calendar read/write scopes", "Assign calendar commands to your role", "Test with 'Show my agenda for today'"] },
  { slug: "gmail", name: "Gmail", category: "Productivity", headline: "Voice-Powered Gmail for Enterprise Teams", description: "Draft, send, and triage emails with authenticated voice commands. Every email action is logged with your identity and timestamp.", commands: ["Send daily standup summary to security team", "Flag email from unknown-sender@domain.com", "Draft response to CFO re: Q1 audit", "Mark all newsletter emails as read"], setupSteps: ["Connect Google Workspace account", "Grant Gmail read/compose scopes", "Configure allowed recipient domains in RBAC", "Test with 'Show unread emails from today'"] },
  { slug: "slack", name: "Slack", category: "Communication", headline: "Voice-Commanded Slack for Security Teams", description: "Send messages, trigger workflows, and manage alerts in Slack via biometric-authenticated voice commands with full audit logging.", commands: ["Send incident alert to #security-ops", "Post daily report to #leadership-updates", "Message John Doe: incident resolved", "Create Slack channel for project phoenix"], setupSteps: ["Install AEGIBIT app in your Slack workspace", "Map Slack channels to VoiceCore roles", "Configure notification routing", "Test with 'Send test message to #general'"] },
  { slug: "jira", name: "Jira", category: "Project Management", headline: "Voice-Driven Jira for Agile Security Teams", description: "Create, update, and triage Jira tickets using authenticated voice commands. Every project action is identity-stamped and logged.", commands: ["Create critical bug ticket for auth module", "Assign ticket SEC-8821 to Priya Sharma", "Move sprint backlog items to this sprint", "Generate sprint burndown report"], setupSteps: ["Connect your Atlassian account in VoiceCore", "Map Jira projects to team roles", "Configure ticket creation templates", "Test with 'Show my open tickets'"] },
  { slug: "servicenow", name: "ServiceNow", category: "ITSM", headline: "Voice-Authenticated ServiceNow Operations", description: "Open, update, and resolve ServiceNow incidents and requests using voice commands with biometric authentication and full ITSM audit trail.", commands: ["Open P1 incident for payment gateway outage", "Assign incident INC0082210 to network team", "Request change approval for firewall rule update", "Generate SLA compliance report for this week"], setupSteps: ["Generate ServiceNow API credentials", "Configure VoiceCore ServiceNow connector", "Map ITSM roles to VoiceCore RBAC", "Test with 'Show open critical incidents'"] },
  { slug: "pagerduty", name: "PagerDuty", category: "Incident Management", headline: "Voice-Command PagerDuty Incident Response", description: "Trigger, acknowledge, and resolve PagerDuty incidents through authenticated voice commands during high-pressure response situations.", commands: ["Trigger P1 incident for API gateway failure", "Acknowledge alert PD-88210", "Page on-call engineer for database issue", "Resolve incident and send post-mortem notification"], setupSteps: ["Connect PagerDuty API key in VoiceCore settings", "Map escalation policies to voice commands", "Configure on-call schedule integration", "Test with 'Show active incidents'"] },
  { slug: "splunk", name: "Splunk", category: "SIEM", headline: "Voice-Queried Splunk for Security Operations", description: "Run Splunk queries, pull threat dashboards, and trigger playbooks through authenticated voice commands without breaking your workflow.", commands: ["Query Splunk for failed logins in last hour", "Pull threat dashboard for production environment", "Search Splunk for CVE-2025-0021 indicators", "Export Splunk report for monthly compliance review"], setupSteps: ["Generate Splunk API token with read permissions", "Configure VoiceCore Splunk connector", "Map query templates to voice commands", "Test with 'Show security events from last hour'"] },
  { slug: "microsoft-teams", name: "Microsoft Teams", category: "Communication", headline: "Voice Commands for Microsoft Teams", description: "Send messages, start meetings, and manage Teams channels through authenticated voice commands with complete audit logging.", commands: ["Send message to security team channel", "Start emergency meeting with incident response team", "Share screen in current Teams call", "Post compliance update to all-staff channel"], setupSteps: ["Connect Microsoft 365 account to VoiceCore", "Grant Teams messaging permissions", "Configure channel access by role", "Test with 'Show recent messages in security channel'"] },
  { slug: "github", name: "GitHub", category: "Developer Tools", headline: "Voice-Authenticated GitHub Operations", description: "Open issues, trigger actions, and manage repositories using biometric-authenticated voice commands with full git activity audit trail.", commands: ["Create issue for authentication bug in repo voicecore-api", "Trigger deploy workflow for main branch", "Assign PR 882 to security review team", "Pull vulnerability report for repository"], setupSteps: ["Connect GitHub org account in VoiceCore", "Configure repository access by team role", "Map GitHub Actions to voice triggers", "Test with 'Show open PRs awaiting review'"] },
  { slug: "linear", name: "Linear", category: "Project Management", headline: "Voice-Powered Linear Project Management", description: "Create issues, update cycles, and manage Linear projects through authenticated voice commands that keep your team moving.", commands: ["Create linear issue: authentication bypass edge case", "Move issue LIN-882 to in-progress", "Assign current cycle backlog to security team", "Generate weekly cycle completion report"], setupSteps: ["Connect Linear workspace via OAuth", "Map team spaces to VoiceCore roles", "Configure issue creation templates", "Test with 'Show my assigned issues'"] },
  { slug: "notion", name: "Notion", category: "Knowledge Management", headline: "Voice-Commanded Notion for Enterprise Teams", description: "Create pages, update databases, and retrieve information from Notion using authenticated voice commands with team-level RBAC.", commands: ["Create incident report page in security playbooks", "Update status of project Phoenix to completed", "Pull runbook for database failover procedure", "Add meeting notes to team wiki"], setupSteps: ["Connect Notion workspace in VoiceCore", "Map Notion databases to voice commands", "Configure page creation templates by role", "Test with 'Show security runbooks'"] },
  { slug: "zendesk", name: "Zendesk", category: "Customer Support", headline: "Voice-Driven Zendesk for Support Teams", description: "Triage, assign, and resolve Zendesk tickets through authenticated voice commands with complete support audit trail.", commands: ["Create urgent ticket for enterprise customer AEGIBIT Ltd", "Assign ticket ZD-88210 to senior support engineer", "Escalate VIP customer ticket to product team", "Generate CSAT report for this week"], setupSteps: ["Generate Zendesk API token", "Configure VoiceCore Zendesk connector", "Map support tiers to RBAC roles", "Test with 'Show unassigned urgent tickets'"] },
  { slug: "aws", name: "Amazon Web Services", category: "Cloud Infrastructure", headline: "Voice-Authenticated AWS Operations", description: "Manage AWS infrastructure through biometric-authenticated voice commands with dual-approval for high-risk operations and complete cloud audit trail.", commands: ["Scale up ECS service api-prod to 10 tasks", "Snapshot RDS instance prod-db-mumbai", "Trigger CloudFormation stack update for vpc-security", "Pull AWS cost report for this month"], setupSteps: ["Create IAM role with least-privilege permissions for VoiceCore", "Configure AWS connector with role ARN", "Map high-risk commands to Sudo Mode", "Test with 'Show running EC2 instances in mumbai'"] },
  { slug: "google-cloud", name: "Google Cloud Platform", category: "Cloud Infrastructure", headline: "Voice Commands for Google Cloud Operations", description: "Control GCP resources through authenticated voice commands with full audit trail for every infrastructure action.", commands: ["Scale GKE cluster security-prod to 5 nodes", "Create snapshot of persistent disk prod-data-01", "Grant viewer access to new engineer on project security-ops", "Pull billing report for March"], setupSteps: ["Create GCP service account with scoped permissions", "Download and configure service account key in VoiceCore", "Map GCP projects to team roles", "Test with 'Show running GCE instances'"] },
  { slug: "datadog", name: "Datadog", category: "Observability", headline: "Voice-Queried Datadog Monitoring", description: "Check dashboards, trigger runbooks, and manage alerts in Datadog through authenticated voice commands during incident response.", commands: ["Show error rate dashboard for api-gateway", "Mute datadog alert for scheduled maintenance window", "Pull APM trace for request ID 88210", "Create monitor for latency above 500ms on checkout"], setupSteps: ["Generate Datadog API and app keys", "Configure VoiceCore Datadog connector", "Map dashboards and monitors to voice commands", "Test with 'Show infrastructure health dashboard'"] },
  { slug: "okta", name: "Okta", category: "Identity Management", headline: "Voice-Commanded Okta Identity Operations", description: "Manage users, reset MFA, and audit identity events in Okta through biometric-authenticated voice commands with complete IAM audit trail.", commands: ["Suspend user account john.doe@company.com", "Reset MFA for user priya.sharma@company.com", "Pull Okta access report for contractor team", "Create Okta group for new security project"], setupSteps: ["Create Okta API token with admin scopes", "Configure VoiceCore Okta connector", "Map identity operations to role-appropriate commands", "Test with 'Show recently locked accounts'"] },
  { slug: "crowdstrike", name: "CrowdStrike Falcon", category: "Endpoint Security", headline: "Voice-Driven CrowdStrike Incident Response", description: "Isolate hosts, pull detection reports, and manage CrowdStrike responses through authenticated voice commands during active security incidents.", commands: ["Isolate endpoint CS-WS-044 from network", "Pull CrowdStrike detections for last 24 hours", "Run on-demand scan on finance-laptop-12", "Generate IOC report for incident INC-882"], setupSteps: ["Generate CrowdStrike Falcon API credentials", "Configure VoiceCore CrowdStrike connector", "Map high-risk commands to Sudo Mode with dual-approval", "Test with 'Show active detections'"] },
  { slug: "microsoft-sentinel", name: "Microsoft Sentinel", category: "SIEM", headline: "Voice-Queried Microsoft Sentinel for SOC Teams", description: "Query incidents, run analytics rules, and manage Sentinel workspaces through authenticated voice commands in your SOC environment.", commands: ["Query Sentinel for brute force incidents last 6 hours", "Acknowledge incident SENT-88210", "Run analytics rule for lateral movement detection", "Pull Sentinel security score for this week"], setupSteps: ["Configure Azure AD app registration for VoiceCore", "Grant Sentinel reader and responder roles", "Map Sentinel workspaces to team RBAC", "Test with 'Show active high-severity incidents'"] },
  { slug: "salesforce", name: "Salesforce CRM", category: "CRM", headline: "Voice-Authenticated Salesforce Operations", description: "Update leads, close opportunities, and generate reports in Salesforce through authenticated voice commands with CRM audit logging.", commands: ["Update opportunity AEGIBIT Enterprise to closed-won", "Create lead for contact met at security conference", "Pull quarterly revenue forecast from Salesforce", "Assign account TechCorp to enterprise sales team"], setupSteps: ["Create Salesforce connected app for VoiceCore", "Configure OAuth scopes for CRM access", "Map Salesforce profiles to VoiceCore roles", "Test with 'Show my open opportunities'"] },
  { slug: "confluence", name: "Confluence", category: "Knowledge Management", headline: "Voice-Commanded Confluence Documentation", description: "Create and retrieve Confluence pages through authenticated voice commands that keep your team's knowledge accessible during incidents.", commands: ["Create incident runbook page in security space", "Pull disaster recovery procedure from confluence", "Update network diagram page with new firewall rules", "Search confluence for VPN configuration guide"], setupSteps: ["Connect Atlassian account to VoiceCore", "Map Confluence spaces to team roles", "Configure page creation templates", "Test with 'Show recent security team pages'"] },
];
