export interface UseCase {
  slug: string;
  name: string;
  industry: string;
  headline: string;
  description: string;
  painPoints: string[];
  howItHelps: string[];
  commands: string[];
}

export const useCases: UseCase[] = [
  {
    slug: "soc-teams",
    name: "SOC Team Voice Automation",
    industry: "Cybersecurity",
    headline: "Voice-Powered Security Operations for SOC Teams",
    description: "SOC analysts respond to hundreds of alerts per shift. AEGIBIT VoiceCore lets them triage, escalate, and document incidents through authenticated voice commands — without leaving their consoles.",
    painPoints: ["Alert fatigue from manual triage", "Context switching between tools", "Slow incident documentation", "No audit trail on analyst actions"],
    howItHelps: ["Voice-authenticate and execute triage commands instantly", "Cross-platform SIEM integration via voice", "Auto-log every analyst action to immutable audit trail", "Anomaly detection flags unusual command patterns"],
    commands: ["Escalate incident to tier 2", "Isolate host 192.168.1.45", "Pull threat intel for IP", "Create PagerDuty incident"],
  },
  {
    slug: "it-helpdesk",
    name: "IT Helpdesk Voice Commands",
    industry: "IT Operations",
    headline: "Faster IT Resolution With Voice-Authenticated Commands",
    description: "IT helpdesk teams waste hours on repetitive, low-risk commands. VoiceCore automates these safely — with full authentication and audit logging.",
    painPoints: ["Repetitive ticket resolution tasks", "No audit trail for actions taken", "Password reset fatigue", "Context switching between systems"],
    howItHelps: ["Voice-command common tasks: reset passwords, unlock accounts", "Every action logged with identity and timestamp", "RBAC ensures tier-1 can only do what tier-1 should", "Integration with ServiceNow and Jira"],
    commands: ["Reset password for user john.doe", "Unlock account marketing-team@company.com", "Create ticket for printer outage floor 3", "Escalate ticket 8821 to network team"],
  },
  {
    slug: "incident-response",
    name: "Voice-Driven Incident Response",
    industry: "Security",
    headline: "Respond to Security Incidents Faster With Voice Commands",
    description: "Every second counts during an incident. VoiceCore eliminates the latency between decision and action — with biometric auth ensuring only authorized responders can act.",
    painPoints: ["Slow manual response under pressure", "Identity confusion during incidents", "No real-time audit during chaos", "Multi-tool context switching"],
    howItHelps: ["Sub-300ms voice command execution", "Biometric authentication on every critical action", "Real-time audit log auto-generated during incident", "Dual-approval (Sudo Mode) for high-risk commands"],
    commands: ["Trigger incident response playbook", "Block IP range 203.0.113.0/24", "Notify CISO of active breach", "Pull logs for last 2 hours on web-server-01"],
  },
  {
    slug: "compliance-reporting",
    name: "Automated Compliance Reporting",
    industry: "GRC",
    headline: "Voice-Commanded Compliance for Audit-Ready Teams",
    description: "Compliance teams spend weeks preparing for audits. VoiceCore's immutable audit trail and automated reporting turn months of manual work into voice commands.",
    painPoints: ["Manual audit trail compilation", "Inconsistent evidence collection", "Reporting across siloed systems", "Human error in compliance documentation"],
    howItHelps: ["Every action auto-logged to immutable audit trail", "Voice-command report generation across integrated systems", "SOC 2 and DPDP evidence always audit-ready", "Role-based access ensures only compliance officers can export"],
    commands: ["Generate audit report for Q1 2026", "Export access log for user rohan.mehta", "Flag anomaly in trading desk access patterns", "Prepare ISO 27001 evidence package"],
  },
  {
    slug: "remote-team-management",
    name: "Remote Team Voice Control",
    industry: "HR/Ops",
    headline: "Manage Distributed Teams With Authenticated Voice Commands",
    description: "Remote teams create security blind spots. VoiceCore ensures every remote action is identity-verified, logged, and controllable — regardless of location.",
    painPoints: ["No visibility into remote actions", "VPN fatigue for access control", "Identity verification gaps", "Distributed audit trail management"],
    howItHelps: ["Voice biometrics work from anywhere", "Every remote command logged with geolocation context", "RBAC enforced regardless of network location", "Anomaly detection for off-hours or unusual access"],
    commands: ["Start remote session on dev-server-12", "Provision access for new hire priya.sharma", "Revoke access for offboarded user", "Generate remote access report for this week"],
  },
  {
    slug: "healthcare-voice-assistant",
    name: "Healthcare Voice Assistant",
    industry: "Healthcare",
    headline: "HIPAA-Aligned Voice Automation for Clinical Teams",
    description: "Clinicians need to move fast. VoiceCore gives them voice automation that respects HIPAA, keeps patient data in India, and never lets the wrong person execute the wrong command.",
    painPoints: ["Manual documentation slows patient care", "HIPAA compliance burden", "Identity management for rotating staff", "Data sovereignty requirements"],
    howItHelps: ["Voice-authenticated EHR commands hands-free", "Full HIPAA-aligned audit trail on every action", "India data residency for patient data", "RBAC maps to clinical role hierarchy"],
    commands: ["Pull patient chart for MR-20450", "Schedule follow-up for ward 3B", "Flag medication alert for Dr. Mehta", "Generate discharge summary for patient 8821"],
  },
  {
    slug: "banking-voice-operations",
    name: "Banking Voice Operations",
    industry: "BFSI",
    headline: "RBI-Compliant Voice Operations for Banking Teams",
    description: "Banking operations demand the highest security standards. VoiceCore is the only voice platform built to meet RBI cybersecurity framework requirements with biometric auth and immutable logs.",
    painPoints: ["RBI audit requirements", "Insider threat risk", "Slow approval workflows", "Manual compliance logging"],
    howItHelps: ["Voice biometric identity on every transaction command", "Dual-approval (Sudo Mode) for high-value operations", "Immutable log meets RBI evidence requirements", "Anomaly detection for insider threat"],
    commands: ["Initiate wire transfer approval workflow", "Pull transaction history for account 88210045", "Flag suspicious login for customer 29012", "Generate RBI compliance report for March"],
  },
  {
    slug: "legal-voice-dictation",
    name: "Legal Voice Documentation",
    industry: "Legal",
    headline: "Secure Voice Dictation and Workflow Automation for Legal Teams",
    description: "Legal teams handle confidential data that demands chain-of-custody documentation. VoiceCore provides authenticated voice dictation with tamper-proof evidence trails.",
    painPoints: ["Manual documentation burden", "Chain of custody requirements", "Confidential data exposure risk", "Access control for sensitive matters"],
    howItHelps: ["Authenticated voice dictation with identity timestamp", "Matter-level RBAC — only assigned counsel can access", "Immutable audit trail for chain of custody", "India data residency for client privilege"],
    commands: ["Dictate memo for matter Singh v. TechCorp", "Pull document history for contract 2024-88", "Assign opposing counsel access to discovery folder", "Generate billing record for today"],
  },
  {
    slug: "devops-voice-commands",
    name: "DevOps Voice Automation",
    industry: "Engineering",
    headline: "Voice-Commanded DevOps With Full Audit Trails",
    description: "DevOps engineers execute high-risk commands constantly. VoiceCore brings authentication and auditability to every deployment, rollback, and infrastructure change.",
    painPoints: ["No audit trail on infrastructure commands", "Human error in manual CLI", "Slow approval for production changes", "Identity verification gaps"],
    howItHelps: ["Biometric auth before any production command", "Every infra change logged with engineer identity", "Dual-approval for production deployments", "Voice-command CI/CD pipeline triggers"],
    commands: ["Deploy api-gateway v2.4 to production", "Rollback payments-service to last stable", "Trigger stress test on staging", "Restart web-server cluster eu-west-1"],
  },
  {
    slug: "cx-operations",
    name: "Customer Experience Operations",
    industry: "Operations",
    headline: "Voice-Powered CX Operations for Enterprise Support Teams",
    description: "CX teams manage thousands of customer interactions daily. VoiceCore automates repeat workflows with authentication, keeping sensitive customer data secure.",
    painPoints: ["Manual case routing slows resolution", "Agent identity verification gaps", "No audit on customer data access", "Cross-system context switching"],
    howItHelps: ["Voice-authenticate agents before accessing customer data", "Instant voice-command case routing and escalation", "Full audit log of every data access", "CRM and ticketing integration"],
    commands: ["Pull customer profile for CX-882110", "Escalate case to tier 2 fraud team", "Issue refund for order ORD-20450", "Flag account for manual review"],
  },
  {
    slug: "procurement-voice",
    name: "Procurement Voice Automation",
    industry: "Finance",
    headline: "Authenticated Voice Commands for Procurement Teams",
    description: "Procurement decisions have direct financial impact. VoiceCore ensures every approval, purchase order, and vendor access is authenticated, logged, and RBAC-controlled.",
    painPoints: ["Approval bottlenecks slow procurement", "No audit on verbal approvals", "Vendor access management complexity", "Compliance with spending policies"],
    howItHelps: ["Voice-biometric approval on purchase orders", "Dual-approval for orders above threshold", "Vendor portal access via RBAC", "Full spending audit trail for finance review"],
    commands: ["Approve PO-20450 for INR 5 lakh", "Request vendor quote from TechSupplier Inc.", "Escalate purchase above 10 lakh to CFO", "Generate procurement report for Q1"],
  },
  {
    slug: "security-operations-center",
    name: "Security Operations Center (SOC)",
    industry: "Cybersecurity",
    headline: "Next-Generation SOC Voice Automation",
    description: "Modern SOCs need tools that match the speed of threats. VoiceCore gives analysts authenticated voice control over their entire security toolstack.",
    painPoints: ["Tool sprawl across the SOC", "Slow escalation pathways", "Identity gaps during shift handoffs", "Manual threat documentation"],
    howItHelps: ["Single voice interface across all SOC tools", "Instant biometric-authenticated escalation", "Auto-document every analyst action in real-time", "SIEM integration for voice-commanded queries"],
    commands: ["Query SIEM for CVE-2025-0021 indicators", "Isolate compromised endpoint SEC-WS-044", "Page on-call analyst for P1 incident", "Generate shift handoff report"],
  },
  {
    slug: "financial-trading-desk",
    name: "Financial Trading Desk",
    industry: "BFSI",
    headline: "Voice-Authenticated Operations for Trading Desks",
    description: "Trading desks require split-second decisions with zero room for identity fraud. VoiceCore provides real-time biometric authentication on every voice command.",
    painPoints: ["Speed-critical environment", "Regulatory mandate for action audit", "Insider trading risk", "Multi-system workflow complexity"],
    howItHelps: ["Sub-300ms biometric auth doesn't slow trading", "Every action timestamped and identity-signed", "Anomaly detection for unusual trading commands", "SEBI-ready audit trail"],
    commands: ["Execute buy order HDFC 500 shares market price", "Pull risk exposure report for equity desk", "Flag unusual trading pattern desk-4", "Generate EOD compliance log"],
  },
  {
    slug: "cloud-infrastructure",
    name: "Cloud Infrastructure Management",
    industry: "IT Operations",
    headline: "Voice-Commanded Cloud Infrastructure With Full Auditability",
    description: "Cloud infrastructure commands can bring down production. VoiceCore adds biometric authentication and dual-approval to every high-risk cloud operation.",
    painPoints: ["No audit trail on cloud CLI commands", "Human error in high-stakes operations", "Slow approval for production changes", "Multi-cloud complexity"],
    howItHelps: ["Biometric auth before any cloud resource change", "Dual-approval (Sudo Mode) for prod operations", "Cross-cloud audit trail in one place", "RBAC aligned to cloud team hierarchy"],
    commands: ["Scale up ECS cluster api-prod to 10 instances", "Snapshot RDS production database", "Revoke IAM role dev-access-prod", "Trigger failover to dr-region-mumbai"],
  },
  {
    slug: "hr-operations",
    name: "HR Operations Voice Automation",
    industry: "Human Resources",
    headline: "Secure Voice Automation for HR Teams",
    description: "HR teams manage sensitive employee data. VoiceCore ensures every access is authenticated, every action audited, and sensitive data never reaches the wrong hands.",
    painPoints: ["Sensitive employee data exposure risk", "Manual onboarding/offboarding workflows", "Compliance with employee data protection laws", "Identity verification for remote HR"],
    howItHelps: ["Biometric auth before accessing employee records", "Voice-commanded onboarding and offboarding workflows", "DPDP Act 2023 compliant data handling", "Full audit trail on all employee data access"],
    commands: ["Onboard new employee Priya Sharma starting Monday", "Revoke all access for offboarded user rahul.kumar", "Pull performance data for Q1 review team", "Generate headcount report for leadership"],
  },
];
